export interface Car {
  id: string;
  make: string;
  model: string;
  year: number;
  price: number;
  mileage: number;
  fuelType: "Petrol" | "Diesel" | "Electric" | "Hybrid";
  transmission: "Automatic" | "Manual";
  bodyType: string;
  color: string;
  engine: string;
  horsepower: number;
  torque: string;
  acceleration: string;
  topSpeed: string;
  seats: number;
  doors: number;
  condition: "New" | "Used" | "Certified Pre-Owned";
  featured: boolean;
  images: string[];
  description: string;
  features: string[];
  badge?: string;
}

export const cars: Car[] = [
  {
    id: "1",
    make: "Rolls-Royce",
    model: "Phantom",
    year: 2024,
    price: 580000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Midnight Black",
    engine: "6.75L V12 Twin-Turbo",
    horsepower: 563,
    torque: "900 Nm",
    acceleration: "5.1s 0-100 km/h",
    topSpeed: "250 km/h",
    seats: 5,
    doors: 4,
    condition: "New",
    featured: true,
    images: [
      "/images/rolls-royce-phantom-black-luxury.jpg",
      "/images/rolls-royce-phantom-interior.jpg",
      "/images/rolls-royce-phantom-side-view.jpg",
    ],
    description:
      "The Rolls-Royce Phantom is the pinnacle of automotive luxury. Every detail is crafted to perfection, offering an unparalleled driving experience that transcends ordinary transportation.",
    features: [
      "Starlight Headliner",
      "Bespoke Audio System",
      "Massage Seats",
      "Night Vision",
      "Head-Up Display",
      "Panoramic Sunroof",
      "Rear Entertainment System",
      "Champagne Cooler",
    ],
    badge: "Flagship",
  },
  {
    id: "2",
    make: "Bentley",
    model: "Continental GT",
    year: 2024,
    price: 245000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Onyx Black",
    engine: "6.0L W12 Twin-Turbo",
    horsepower: 650,
    torque: "900 Nm",
    acceleration: "3.6s 0-100 km/h",
    topSpeed: "333 km/h",
    seats: 4,
    doors: 2,
    condition: "New",
    featured: true,
    images: [
      "/images/bentley-continental-gt-black-coupe.jpg",
      "/images/bentley-continental-gt-interior-luxury.jpg",
      "/images/bentley-continental-gt-rear.jpg",
    ],
    description:
      "The Bentley Continental GT is a grand tourer that combines breathtaking performance with handcrafted luxury. A masterpiece of British engineering.",
    features: [
      "Rotating Display",
      "Naim Audio System",
      "Heated/Cooled Seats",
      "All-Wheel Drive",
      "Active All-Wheel Steering",
      "Carbon Ceramic Brakes",
      "Mood Lighting",
      "Wireless Charging",
    ],
    badge: "Best Seller",
  },
  {
    id: "3",
    make: "Lamborghini",
    model: "Urus S",
    year: 2024,
    price: 320000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Nero Noctis",
    engine: "4.0L V8 Twin-Turbo",
    horsepower: 666,
    torque: "850 Nm",
    acceleration: "3.5s 0-100 km/h",
    topSpeed: "305 km/h",
    seats: 5,
    doors: 4,
    condition: "New",
    featured: true,
    images: [
      "/images/lamborghini-urus-s-black-suv.jpg",
      "/images/lamborghini-urus-s-interior.jpg",
      "/images/lamborghini-urus-s-front.jpg",
    ],
    description:
      "The Lamborghini Urus S redefines the Super SUV segment. Combining supercar DNA with everyday usability, it delivers an exhilarating experience unlike any other.",
    features: [
      "Lamborghini Infotainment System",
      "Bang & Olufsen Sound",
      "Air Suspension",
      "Torque Vectoring",
      "Off-Road Mode",
      "Carbon Fiber Package",
      "Sport Exhaust",
      "Panoramic Roof",
    ],
    badge: "Hot",
  },
  {
    id: "4",
    make: "Ferrari",
    model: "Roma",
    year: 2023,
    price: 285000,
    mileage: 1200,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Nero Daytona",
    engine: "3.9L V8 Twin-Turbo",
    horsepower: 612,
    torque: "760 Nm",
    acceleration: "3.4s 0-100 km/h",
    topSpeed: "320 km/h",
    seats: 4,
    doors: 2,
    condition: "Certified Pre-Owned",
    featured: true,
    images: [
      "/images/ferrari-roma-black-coupe.jpg",
      "/images/ferrari-roma-interior-cockpit.jpg",
      "/images/ferrari-roma-side-profile.jpg",
    ],
    description:
      "The Ferrari Roma embodies the spirit of la dolce vita. Its elegant design and thrilling performance make it the perfect grand tourer for those who demand the best.",
    features: [
      "Ferrari Dynamic Enhancer",
      "Manettino Dial",
      "JBL Premium Audio",
      "Adaptive Suspension",
      "Carbon Fiber Trim",
      "Heated Seats",
      "Rear Camera",
      "Apple CarPlay",
    ],
    badge: "CPO",
  },
  {
    id: "5",
    make: "Porsche",
    model: "Cayenne Turbo GT",
    year: 2024,
    price: 195000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Jet Black Metallic",
    engine: "4.0L V8 Twin-Turbo",
    horsepower: 640,
    torque: "850 Nm",
    acceleration: "3.3s 0-100 km/h",
    topSpeed: "300 km/h",
    seats: 5,
    doors: 4,
    condition: "New",
    featured: false,
    images: [
      "/images/porsche-cayenne-turbo-gt-black.jpg",
      "/images/porsche-cayenne-turbo-gt-interior.jpg",
      "/images/porsche-cayenne-turbo-gt-rear.jpg",
    ],
    description:
      "The Porsche Cayenne Turbo GT is the most powerful Cayenne ever built. Track-focused engineering meets everyday luxury in this extraordinary SUV.",
    features: [
      "PASM Sport Suspension",
      "Porsche Torque Vectoring Plus",
      "Bose Surround Sound",
      "Sport Chrono Package",
      "Carbon Ceramic Brakes",
      "Panoramic Roof",
      "Night Vision Assist",
      "Head-Up Display",
    ],
  },
  {
    id: "6",
    make: "Mercedes-Benz",
    model: "S 680 Maybach",
    year: 2024,
    price: 420000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Obsidian Black",
    engine: "6.0L V12 Biturbo",
    horsepower: 612,
    torque: "1000 Nm",
    acceleration: "4.5s 0-100 km/h",
    topSpeed: "250 km/h",
    seats: 4,
    doors: 4,
    condition: "New",
    featured: true,
    images: [
      "/images/mercedes-maybach-s680-black-luxury.jpg",
      "/images/mercedes-maybach-s680-rear-interior.jpg",
      "/images/mercedes-maybach-s680-front.jpg",
    ],
    description:
      "The Mercedes-Maybach S 680 represents the ultimate in automotive luxury. With its extended wheelbase and V12 engine, it offers an experience reserved for the world's elite.",
    features: [
      "Executive Rear Seats",
      "Burmester 4D Sound",
      "Magic Body Control",
      "Rear Axle Steering",
      "Energizing Comfort",
      "Fragrance System",
      "Champagne Flutes",
      "Partition Window",
    ],
    badge: "Ultra Luxury",
  },
  {
    id: "7",
    make: "Aston Martin",
    model: "DB12",
    year: 2024,
    price: 265000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Jet Black",
    engine: "4.0L V8 Twin-Turbo",
    horsepower: 671,
    torque: "800 Nm",
    acceleration: "3.6s 0-100 km/h",
    topSpeed: "325 km/h",
    seats: 4,
    doors: 2,
    condition: "New",
    featured: false,
    images: [
      "/images/aston-martin-db12-black-coupe.jpg",
      "/images/aston-martin-db12-interior.jpg",
      "/images/aston-martin-db12-rear.jpg",
    ],
    description:
      "The Aston Martin DB12 is the world's first Super Tourer. It combines breathtaking performance with refined luxury in a package of timeless British elegance.",
    features: [
      "Aston Martin Sound System",
      "Adaptive Damping",
      "Electronic Rear Differential",
      "Carbon Fiber Roof",
      "Heated/Ventilated Seats",
      "360° Camera",
      "Wireless Charging",
      "Ambient Lighting",
    ],
  },
  {
    id: "8",
    make: "BMW",
    model: "M8 Competition",
    year: 2023,
    price: 145000,
    mileage: 5800,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Black Sapphire",
    engine: "4.4L V8 Twin-Turbo",
    horsepower: 625,
    torque: "750 Nm",
    acceleration: "3.2s 0-100 km/h",
    topSpeed: "305 km/h",
    seats: 4,
    doors: 2,
    condition: "Certified Pre-Owned",
    featured: false,
    images: [
      "/images/bmw-m8-competition-black-coupe.jpg",
      "/images/bmw-m8-competition-interior.jpg",
      "/images/bmw-m8-competition-front.jpg",
    ],
    description:
      "The BMW M8 Competition is the ultimate expression of M performance. Combining supercar performance with grand tourer comfort, it's a car that does everything brilliantly.",
    features: [
      "M xDrive All-Wheel Drive",
      "Bowers & Wilkins Sound",
      "M Carbon Ceramic Brakes",
      "Active M Differential",
      "Head-Up Display",
      "Laser Headlights",
      "Gesture Control",
      "Parking Assistant",
    ],
  },
  {
    id: "9",
    make: "McLaren",
    model: "720S",
    year: 2023,
    price: 310000,
    mileage: 2100,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Onyx Black",
    engine: "4.0L V8 Twin-Turbo",
    horsepower: 720,
    torque: "770 Nm",
    acceleration: "2.9s 0-100 km/h",
    topSpeed: "341 km/h",
    seats: 2,
    doors: 2,
    condition: "Certified Pre-Owned",
    featured: false,
    images: [
      "/images/mclaren-720s-black-supercar.jpg",
      "/images/mclaren-720s-interior-cockpit.jpg",
      "/images/mclaren-720s-side.jpg",
    ],
    description:
      "The McLaren 720S is a technological tour de force. Its carbon fiber MonoCell II chassis and twin-turbocharged V8 deliver a driving experience that borders on the supernatural.",
    features: [
      "Carbon Fiber MonoCell II",
      "Proactive Chassis Control II",
      "Variable Drift Control",
      "Folding Driver Display",
      "Electrochromic Roof",
      "Bowers & Wilkins Audio",
      "Track Telemetry",
      "Launch Control",
    ],
  },
  {
    id: "10",
    make: "Bentley",
    model: "Bentayga EWB",
    year: 2024,
    price: 295000,
    mileage: 0,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Beluga Black",
    engine: "3.0L V6 Hybrid",
    horsepower: 462,
    torque: "700 Nm",
    acceleration: "5.2s 0-100 km/h",
    topSpeed: "254 km/h",
    seats: 7,
    doors: 4,
    condition: "New",
    featured: false,
    images: [
      "/images/bentley-bentayga-ewb-black-suv.jpg",
      "/images/bentley-bentayga-ewb-rear-seats.jpg",
      "/images/bentley-bentayga-ewb-front.jpg",
    ],
    description:
      "The Bentley Bentayga Extended Wheelbase is the most luxurious SUV in the world. Its extended rear cabin offers first-class comfort for the most discerning passengers.",
    features: [
      "Airline Seat Specification",
      "Naim for Bentley Audio",
      "Bentley Dynamic Ride",
      "All-Terrain Specification",
      "Rear Entertainment",
      "Massage Seats",
      "Refrigerator",
      "Panoramic Sunroof",
    ],
  },
  {
    id: "11",
    make: "Porsche",
    model: "911 Turbo S",
    year: 2024,
    price: 235000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Black",
    engine: "3.8L Flat-6 Twin-Turbo",
    horsepower: 650,
    torque: "800 Nm",
    acceleration: "2.7s 0-100 km/h",
    topSpeed: "330 km/h",
    seats: 4,
    doors: 2,
    condition: "New",
    featured: false,
    images: [
      "/images/porsche-911-turbo-s-black.jpg",
      "/images/porsche-911-turbo-s-interior.jpg",
      "/images/porsche-911-turbo-s-rear.jpg",
    ],
    description:
      "The Porsche 911 Turbo S is the definitive sports car. Decades of motorsport heritage distilled into the most capable 911 ever made.",
    features: [
      "PDCC Sport",
      "PCCB Carbon Ceramic Brakes",
      "Sport Chrono Package",
      "Burmester Sound System",
      "Rear-Axle Steering",
      "Night Vision Assist",
      "Adaptive Cruise Control",
      "Wireless Apple CarPlay",
    ],
  },
  {
    id: "12",
    make: "Tesla",
    model: "Model S Plaid",
    year: 2024,
    price: 135000,
    mileage: 0,
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Midnight Black",
    engine: "Tri-Motor Electric",
    horsepower: 1020,
    torque: "1420 Nm",
    acceleration: "2.1s 0-100 km/h",
    topSpeed: "322 km/h",
    seats: 5,
    doors: 4,
    condition: "New",
    featured: false,
    images: [
      "/images/tesla-model-s-plaid-black.jpg",
      "/images/tesla-model-s-plaid-interior.jpg",
      "/images/tesla-model-s-plaid-front.jpg",
    ],
    description:
      "The Tesla Model S Plaid is the quickest production car ever made. With over 1,000 horsepower and a 0-100 km/h time of 2.1 seconds, it redefines what an electric car can be.",
    features: [
      "Autopilot",
      "Full Self-Driving Capability",
      "17-inch Touchscreen",
      "Premium Audio System",
      "Over-the-Air Updates",
      "Supercharger Network",
      "Gaming Computer",
      "Bioweapon Defense Mode",
    ],
    badge: "Electric",
  },
];

export const testimonials = [
  {
    id: "1",
    name: "Alexander Thornton",
    role: "CEO, Thornton Industries",
    avatar: "/images/testimonial-executive-man.jpg",
    rating: 5,
    text: "Purchasing my Rolls-Royce Phantom through Aurum Motors was an experience unlike any other. The team's attention to detail and white-glove service exceeded every expectation. Truly world-class.",
  },
  {
    id: "2",
    name: "Victoria Harrington",
    role: "Fashion Designer",
    avatar: "/images/testimonial-elegant-woman.jpg",
    rating: 5,
    text: "I've bought three cars from Aurum Motors and each time the experience gets better. They understand that buying a luxury car is about more than just the vehicle — it's about the entire journey.",
  },
  {
    id: "3",
    name: "James Whitfield",
    role: "Investment Banker",
    avatar: "/images/testimonial-professional-man.jpg",
    rating: 5,
    text: "The team at Aurum Motors found me the perfect Bentley Continental GT. Their knowledge of the vehicles and their commitment to finding exactly what I wanted was impressive.",
  },
  {
    id: "4",
    name: "Sophia Chen",
    role: "Tech Entrepreneur",
    avatar: "/images/testimonial-businesswoman.jpg",
    rating: 5,
    text: "From the moment I walked in, I knew this was different. The showroom is stunning, the staff are impeccably knowledgeable, and the after-sales service is second to none.",
  },
];

export const teamMembers = [
  {
    id: "1",
    name: "Richard Aurum",
    role: "Founder & CEO",
    image: "/images/team-ceo-luxury-dealership.jpg",
    bio: "With over 25 years in the luxury automotive industry, Richard founded Aurum Motors with a vision to redefine the car buying experience.",
  },
  {
    id: "2",
    name: "Isabella Montague",
    role: "Head of Sales",
    image: "/images/team-sales-director-woman.jpg",
    bio: "Isabella brings 15 years of luxury retail expertise, ensuring every client receives a bespoke, personalized experience from first contact to delivery.",
  },
  {
    id: "3",
    name: "Marcus Sterling",
    role: "Chief Automotive Specialist",
    image: "/images/team-automotive-specialist-man.jpg",
    bio: "A former Formula 1 engineer, Marcus leads our technical team and ensures every vehicle meets our exacting standards before reaching our showroom.",
  },
  {
    id: "4",
    name: "Elena Vasquez",
    role: "Client Relations Director",
    image: "/images/team-client-relations-woman.jpg",
    bio: "Elena oversees our after-sales care program, building lasting relationships with our distinguished clientele across the globe.",
  },
];

export const milestones = [
  { year: "1998", title: "Founded", description: "Aurum Motors established in London with a curated selection of 12 vehicles." },
  { year: "2005", title: "Expansion", description: "Opened our flagship showroom and expanded to 5 major cities across the UK." },
  { year: "2010", title: "International", description: "Launched international operations, serving clients across Europe and the Middle East." },
  { year: "2015", title: "Award Winning", description: "Named 'Luxury Dealer of the Year' for five consecutive years by Automotive Excellence Awards." },
  { year: "2020", title: "Digital Innovation", description: "Launched our virtual showroom and concierge delivery service worldwide." },
  { year: "2024", title: "Today", description: "Over 2,500 satisfied clients, 200+ vehicles in stock, and a legacy of uncompromising excellence." },
];

export const brands = ["All", "Rolls-Royce", "Bentley", "Lamborghini", "Ferrari", "Porsche", "Mercedes-Benz", "Aston Martin", "BMW", "McLaren", "Tesla"];
export const fuelTypes = ["All", "Petrol", "Diesel", "Electric", "Hybrid"];
export const transmissions = ["All", "Automatic", "Manual"];
export const conditions = ["All", "New", "Used", "Certified Pre-Owned"];
